<template>
    <Transition enterActiveClass="transition ease-out duration-300" enterFromClass="opacity-0"
        enterToClass="opacity-100" leaveActiveClass="transition ease-in duration-200" leaveFromClass="opacity-100"
        leaveToClass="opacity-0">
        <div v-if="isOpen" class="fixed inset-0 bg-black/50 backdrop-blur-sm z-40" @click="close">
        </div>
    </Transition>

    <Transition enterActiveClass="transition ease-out duration-300" enterFromClass="opacity-0 scale-95"
        enterToClass="opacity-100 scale-100" leaveActiveClass="transition ease-in duration-200"
        leaveFromClass="opacity-100 scale-100" leaveToClass="opacity-0 scale-95">
        <div v-if="isOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4" @click.self="close">
            <div class="bg-white rounded-3xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col">
                <div class="bg-gradient-to-r from-[#1E71B8] to-[#008DDA] px-8 py-6 flex items-center justify-between">
                    <h2 class="text-2xl font-bold text-white tracking-wide">Terms & Conditions</h2>
                    <button @click="close"
                        class="text-white/80 hover:text-white transition-all duration-200 p-1 hover:scale-110">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div class="overflow-y-auto flex-1 px-8 py-8 space-y-6 text-gray-700 text-sm leading-relaxed">
                    <p class="font-semibold text-[#1E71B8] mb-4">
                        Welcome to JE Travel & Tours. By accessing our website, using our booking system, or availing of
                        our services, you agree to be bound by these Terms and Conditions. Please read them carefully.
                    </p>

                    <div class="border-l-4 border-[#73BE5D] pl-5">
                        <h3 class="text-lg font-bold text-[#1E71B8] mb-4">GENERAL WEBSITE & SYSTEM USE</h3>

                        <div class="space-y-4 ml-2">
                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">1. Usage</h4>
                                <p>Users of this system must be at least eighteen (18) years of age and have the legal
                                    capacity to enter into binding contracts. You are responsible for maintaining the
                                    confidentiality of your account credentials used in our system. You are financially
                                    responsible for all uses of our system by you and anyone using your login
                                    information.</p>
                            </div>

                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">2. Prohibited Acts</h4>
                                <p class="mb-2">The content, infrastructure, and software code of this system are
                                    proprietary to JE Travel & Tours. You agree not to:</p>
                                <ul class="list-disc list-inside space-y-1 ml-2">
                                    <li>Use this website for any fraudulent or speculative reservation.</li>
                                    <li>"Scrape," "hack," or "data mine" our infrastructure.</li>
                                    <li>Reproduce, sell, or trade travel itineraries generated by this system without
                                        permission.</li>
                                </ul>
                            </div>

                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">3. Intellectual Property</h4>
                                <p>All trademarks, logos, and service marks displayed are the property of JE Travel &
                                    Tours. You are granted a limited license to print travel itineraries for personal
                                    use only.</p>
                            </div>
                        </div>
                    </div>

                    <div class="border-l-4 border-[#008DDA] pl-5">
                        <h3 class="text-lg font-bold text-[#1E71B8] mb-4">BOOKING TERMS & CONDITIONS (The Contract)</h3>

                        <div class="space-y-4 ml-2">
                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">1. Scope of Services (Domestic Only)</h4>
                                <p>JE Travel & Tours specializes in domestic travel within the Philippines. We arrange
                                    transport, accommodation, and tours within the country. We act as an agent for
                                    third-party suppliers (domestic airlines, shipping lines/ferries, bus operators,
                                    hotels, and local tour operators).</p>
                            </div>

                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">2. Payment Policy</h4>
                                <p class="mb-3">To secure a booking with JE Travel & Tours, the following schedule
                                    applies. Please note that all deadlines are strictly based on your Scheduled Tour
                                    Date.</p>
                                <ul class="space-y-2 ml-2">
                                    <li><span class="font-semibold">Down Payment (Booking Confirmation):</span> A
                                        partial down payment ranging from 20% to 50% of the total cost is required to
                                        officially reserve your slot in our system. Until this down payment is received
                                        and recorded, your booking is considered "Provisional" and the slot remains open
                                        to other guests.</li>
                                    <li><span class="font-semibold">Payment Deadline:</span> Strict Deadline: ALL
                                        payments (both the initial Down Payment and the Remaining Balance) must be fully
                                        settled, verified, and recorded in our system no later than 3 Days before the
                                        scheduled tour date.</li>
                                    <li><span class="font-semibold">Failure to Pay:</span> If the full balance is not
                                        received by the 3-day cutoff, JE Travel & Tours reserves the right to cancel
                                        your booking automatically. In this event, any previously paid down payment will
                                        be forfeited in accordance with our Non-Refundable policy.</li>
                                </ul>
                            </div>

                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">3. Cancellation & Refund Policy (Voluntary
                                    Cancellation)</h4>
                                <ul class="space-y-2 ml-2">
                                    <li><span class="font-semibold">Strict No Refund Policy:</span> For voluntary
                                        cancellations made by the guest (e.g., "change of mind," "personal conflict"),
                                        payments made are generally NON-REFUNDABLE.</li>
                                    <li><span class="font-semibold">Replacement Option:</span> If you cannot proceed
                                        with the travel, you are allowed to transfer your slot to another person. You
                                        must provide a Replacement Passenger to take your place. You must notify JE
                                        Travel & Tours of the name change at least 3 days before departure. Any fees
                                        charged by third-party suppliers for name changes (e.g., Airline Re-booking
                                        Fees) shall be shouldered by the customer.</li>
                                </ul>
                            </div>

                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">4. Natural Disasters & Force Majeure
                                    (Negotiable Refunds)</h4>
                                <p class="mb-2">JE Travel & Tours is not generally liable for failure to perform
                                    obligations due to events beyond our control (e.g., Typhoons, Earthquakes, Volcanic
                                    Eruptions, Government Travel Bans/Lockdowns). However, we handle these situations as
                                    follows:</p>
                                <ul class="space-y-2 ml-2">
                                    <li><span class="font-semibold">Notification:</span> We will notify you regarding
                                        cancellations or changes via Email and Phone Call.</li>
                                    <li><span class="font-semibold">Rescheduling:</span> Our primary recourse is to
                                        facilitate a Change of Travel Date to a safer time.</li>
                                    <li><span class="font-semibold">Negotiable Refunds:</span> In the specific case of
                                        Natural Disasters or Force Majeure, refund requests are negotiable and subject
                                        to review. Approval of refunds is contingent upon the refund policies of our
                                        Third-Party Suppliers (e.g., if the Airline or Ferry refunds us, we will process
                                        a refund to you). Service fees or administrative fees may still be deducted from
                                        the refund amount to cover agency processing costs.</li>
                                </ul>
                            </div>

                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">5. Domestic Travel Documents</h4>
                                <p class="mb-2">It is the traveler's responsibility to possess valid identification
                                    required for domestic travel.</p>
                                <ul class="space-y-2 ml-2">
                                    <li><span class="font-semibold">Valid ID:</span> You must present a valid
                                        Government-Issued ID (e.g., Driver's License, UMID, Postal ID, Passport) at
                                        airports and seaports.</li>
                                    <li><span class="font-semibold">Minors:</span> Travelers below 18 years old must be
                                        accompanied by a parent/guardian or possess the necessary DSWD clearance if
                                        traveling alone, along with a PSA Birth Certificate.</li>
                                    <li>JE Travel & Tours is not liable if you are denied boarding due to failure to
                                        present valid identification.</li>
                                </ul>
                            </div>

                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">6. Insurance</h4>
                                <p>Travel insurance is strongly recommended, even for domestic travel, to cover
                                    potential medical emergencies or lost baggage.</p>
                            </div>

                            <div>
                                <h4 class="font-bold text-gray-800 mb-2">7. Jurisdiction</h4>
                                <p>These terms shall be governed by the laws of the Republic of the Philippines. Any
                                    legal disputes arising from this agreement shall be settled exclusively in the
                                    courts of Binan, Laguna.</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="bg-gray-50 px-8 py-5 flex justify-end border-t border-gray-200">
                    <button @click="close"
                        class="px-6 py-2.5 bg-gradient-to-r from-[#1E71B8] to-[#008DDA] text-white font-semibold rounded-lg hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300">
                        Close
                    </button>
                </div>
            </div>
        </div>
    </Transition>
</template>

<script setup>
import { defineProps, defineEmits } from 'vue'

defineProps({
    isOpen: Boolean
})

const emit = defineEmits(['close'])

const close = () => {
    emit('close')
}
</script>